language: c++
compiler: clang
branches:
    only:
        - master
os:
    - linux
    - osx
sudo: true
dist: trusty
addons:
    apt:
        sources:
            - kubuntu-backports
            - llvm-toolchain-trusty
        packages:
            - cmake
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - clang-5.0
env:
    - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
# before_install:
  # - mkdir $HOME/usr
  # - export PATH="$HOME/usr/bin:$PATH"
  # - wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh
  # - chmod +x cmake-3.7.2-Linux-x86_64.sh
  # - ./cmake-3.7.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
script:
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-5.0" CC="clang-5.0";
    - sudo env "PATH=$PATH" cmake -G "Unix Makefiles"
    - sudo env "PATH=$PATH" make
notifications:
    email:
        recipients:
            - mueller.vpr@gmail.com
    on_success: always
    on_failure: always