language: c
compiler: clang
branches:
    only:
        - master
os:
    - linux
    - osx
sudo: false
dist: trusty
addons:
    apt:
        sources:
            - kubuntu-backports
        packages:
            - cmake
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
script:
	- premake5-linux-64
	- make
notifications:
    email:
        recipients:
            - mueller.vpr@gmail.com
    on_success: always
    on_failure: always