language: c++
compiler: clang
branches:
    only:
        - master
os:
    - linux
    - osx
sudo: true
dist: trusty
addons:
    apt:
        sources:
            - kubuntu-backports
            - llvm-toolchain-trusty
        packages:
            - cmake
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - clang-5.0
env:
    - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then PREMAKE=./premake5-linux-64; else PREMAKE=./premake5-osx; fi
    - chmod u+x $PREMAKE
    - $PREMAKE
    - make
notifications:
    email:
        recipients:
            - mueller.vpr@gmail.com
    on_success: always
    on_failure: always