# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  FirstChapter_config = debug
endif
ifeq ($(config),release)
  FirstChapter_config = release
endif

PROJECTS := FirstChapter

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

FirstChapter:
ifneq (,$(FirstChapter_config))
	@echo "==== Building FirstChapter ($(FirstChapter_config)) ===="
	@${MAKE} --no-print-directory -C src/FirstChapter -f Makefile config=$(FirstChapter_config)
endif

clean:
	@${MAKE} --no-print-directory -C src/FirstChapter -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   FirstChapter"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"